drop TABLE if EXISTS Albums;
drop TABLE if EXISTS Genres;
drop TABLE if EXISTS Users;


CREATE TABLE IF NOT EXISTS Users (
    Id_user INTEGER PRIMARY KEY AUTOINCREMENT,
    Name_user VARCHAR(100) NOT NULL,
    Firstname VARCHAR(100) NOT NULL,
    Birthdate DATE NOT NULL,
    Genre VARCHAR(100) NOT NULL
  );

CREATE TABLE IF NOT EXISTS Genres (
Id_genre INTEGER PRIMARY KEY AUTOINCREMENT,
Name_genre VARCHAR(100) NOT NULL,
user_id INTEGER,
FOREIGN KEY (user_id) REFERENCES Users(Id_user)
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Albums (
    Id_album INTEGER PRIMARY KEY AUTOINCREMENT,
    Name_album VARCHAR(100) NOT NULL,
    genre_id INTEGER,
    FOREIGN KEY (genre_id) REFERENCES Genres(Id_genre)
    ON DELETE CASCADE
);